app:
  security:
    allowedOrigins: http://localhost:8080

server:
  port: 8090
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rig_db
    username: admin
    password: admin
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092