server:
  port: 8110
  shutdown: graceful

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@host.docker.internal:27017/rig_history_db?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092
